export const UPDATE_OFFERINGS = "UPDATE_OFFERINGS";
export const UPDATE_SUBJECTS = "UPDATE_SUBJECTS";
export const UPDATE_CURRENT_SUBJECT = "UPDATE_CURRENT_SUBJECT";

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_MULTIPLE_TO_CART = 'ADD_MULTIPLE_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';
export const TOGGLE_CART = 'TOGGLE_CART';
export const ADD_TUTOR_TIMEWINDOW = 'ADD_TUTOR_TIMEWINDOW';
export const BOOK_TUTOR_TIMEWINDOW = 'BOOK_TUTOR_TIMEWINDOW';
export const REMOVE_TUTOR_TIMEWINDOW = 'REMOVE_TUTOR_TIMEWINDOW';


// export const UPDATE_USER = 'UPDATE_USER';

